# Generated by Django 5.2.8 on 2025-12-01 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provaSaep', '0002_alter_historico_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='nome',
            field=models.CharField(default='Sem nome', max_length=100),
        ),
    ]
